import type { NextPage } from 'next'
import Head from 'next/head'
import { Post } from '@local/post'

const Home: NextPage = () => {
  return (
    <div className="p-40">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post />
    </div>
  )
}

export default Home
